CREATE TABLE IF NOT EXISTS users (
    telegram_id BIGINT NOT NULL,
    PRIMARY KEY (telegram_id),
    username VARCHAR(256),
    first_name VARCHAR(256),
    last_name VARCHAR(256),
    is_premium BOOLEAN NOT NULL DEFAULT FALSE,
) CREATE TABLE IF NOT EXISTS categories (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    icon VARCHAR(256),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
) CREATE TABLE IF NOT EXISTS services (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    icon VARCHAR(256),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
) CREATE TABLE IF NOT EXISTS portfolio (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    image VARCHAR(256),
    link VARCHAR(256),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    service_id BIGINT NOT NULL,
    FOREIGN KEY (service_id) REFERENCES services(id),
) CREATE TABLE IF NOT EXISTS portfolio_items (
    id SERIAL PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    image VARCHAR(256),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (portfolio_id) REFERENCES portfolio(id),
)